export const USER_ELASTICSEARCH_INDEX = 'users'
export const REFRESH_TOKEN_USER_ELASTICSEARCH_INDEX = 'refresh-tokens-user'
export const BOOK_TABLE_ELASTICSEARCH_INDEX = 'book-table'
export const AMENITY_ELASTICSEARCH_INDEX = 'amenities'
export const CATEGORY_ELASTICSEARCH_INDEX = 'category'
export const RESTAURANT_TYPE_ELASTICSEARCH_INDEX = 'restaurant-type'
export const UPLOAD_ELASTICSEARCH_INDEX = 'upload'
export const ROLE_ELASTICSEARCH_INDEX = 'role'
export const ROLE_PERMISSION_ELASTICSEARCH_INDEX = 'role-permission'
export const TABLE_ELASTICSEARCH_INDEX = 'tables'
export const ORDER_DISH_SUMMARY_ELASTICSEARCH_INDEX = 'order-dish-summary'
export const GUEST_RESTAURANT_ELASTICSEARCH_INDEX = 'guest-restaurant'
export const ORDER_DISH_ELASTICSEARCH_INDEX = 'order-dish'
export const DISH_ELASTICSEARCH_INDEX = 'dishes'
export const DISH_DUPLICATE_ELASTICSEARCH_INDEX = 'dish-duplicate'
export const BLOG_ELASTICSEARCH_INDEX = 'blogs'
export const TAG_BLOG_ELASTICSEARCH_INDEX = 'tag-blog'
export const COMMENT_BLOG_ELASTICSEARCH_INDEX = 'comment-blog'
export const CATEGORY_RESTAURANT_ELASTICSEARCH_INDEX = 'category-restaurant'
export const EMPLOYEE_ELASTICSEARCH_INDEX = 'employees'
export const RESTAURANT_ELASTICSEARCH_INDEX = 'restaurants'
export const ACCOUNT_ELASTICSEARCH_INDEX = 'accounts'
export const REFRESH_TOKEN_ACCOUNT_ELASTICSEARCH_INDEX = 'refresh-tokens-account'

export const FOOD_RESTAURANT_ELASTICSEARCH_INDEX = 'food-restaurant'
export const FOOD_OPTIONS_ELASTICSEARCH_INDEX = 'food-options'
export const FOOD_COMBO_RES_ELASTICSEARCH_INDEX = 'food-combo-res'
export const FOOD_COMBO_ITEM_ELASTICSEARCH_INDEX = 'food-combo-item'

export const WORKING_SHIFT_ELASTICSEARCH_INDEX = 'working-shift'
export const SHIFT_ASSIGNMENT_ELASTICHSEARCH_INDEX = 'shift-assignment'

export const TICKET_GUEST_RESTAURANT_ELASTICSEARCH_INDEX = 'ticket-guest-restaurant'
export const TICKET_GUEST_RESTAURANT_REPLICES_ELASTICSEARCH_INDEX = 'ticket-guest-restaurant-replices'

export const NOTIFICATION_EMPLOYEE_ELASTICSEARCH_INDEX = 'notification-employee'

export const SUPPLIER_ELASTICSEARCH_INDEX = 'suppliers'
export const CAT_INGREDIENT_ELASTICSEARCH_INDEX = 'cat-ingredients'
export const UNIT_ELASTICSEARCH_INDEX = 'units'
export const UNIT_CONVERSION_ELASTICSEARCH_INDEX = 'unit-conversion'
export const INGREDIENT_ELASTICSEARCH_INDEX = 'ingredients'
export const STOCK_IN_ELASTICSEARCH_INDEX = 'stock-in'
export const STOCK_IN_ITEM_ELASTICSEARCH_INDEX = 'stock-in-item'
export const STOCK_OUT_ELASTICSEARCH_INDEX = 'stock-out'
export const STOCK_OUT_ITEM_ELASTICSEARCH_INDEX = 'stock-out-item'

export const MENU_CATEGORY_ELASTICSEARCH_INDEX = 'menu-category'
export const MENU_ITEMS_ELASTICSEARCH_INDEX = 'menu-items'
export const AMENITIES_BOOK_ROOM_ELASTICSEARCH_INDEX = 'amenities-book-room'
export const ROOMS_ELASTICSEARCH_INDEX = 'rooms'

export const PATH_SYSTEM_ELASTICSEARCH_INDEX = 'path-system'
