export const KEY_REGISTER = 'register'
export const KEY_REFRESH_TOKEN = 'refresh_token'
export const KEY_BLACK_LIST_TOKEN_USER = 'black_list_token_user'
export const KEY_FORGOT_PASWORD = 'forgot_password'
export const KEY_BLACK_LIST_TOKEN_RESTAURANT = 'black_list_token_restaurant'
export const KEY_BLACK_LIST_TOKEN_EMPLOYEE = 'black_list_token_employee'
export const KEY_LOGOUT_TABLE_RESTAURANT = 'logout_table_restaurant'
export const KEY_ACCESS_TOKEN_GUEST_RESTAURANT = 'access_token_guest_restaurant'

export const SIGN_TOKEN = 'sign_token'
