// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "category-restaurant.proto" (package "CategoryRestaurantProto", syntax proto3)
// tslint:disable
import { IBackendGRPC } from "./api";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message CategoryRestaurantProto.ReqFindOneCatRes
 */
export interface ReqFindOneCatRes {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string catResId = 2;
     */
    catResId: string;
}
/**
 * @generated from protobuf message CategoryRestaurantProto.CategoryRestaurantModel
 */
export interface CategoryRestaurantModel {
    /**
     * @generated from protobuf field: string cat_res_id = 1;
     */
    catResId: string;
    /**
     * @generated from protobuf field: string cat_res_name = 2;
     */
    catResName: string;
    /**
     * @generated from protobuf field: string cat_res_slug = 3;
     */
    catResSlug: string;
    /**
     * @generated from protobuf field: CategoryRestaurantProto.Image cat_res_icon = 4;
     */
    catResIcon?: Image;
    /**
     * @generated from protobuf field: string cat_res_short_description = 5;
     */
    catResShortDescription: string;
    /**
     * @generated from protobuf field: string cat_res_status = 6;
     */
    catResStatus: string;
    /**
     * @generated from protobuf field: CategoryRestaurantProto.crudBy createdBy = 7;
     */
    createdBy?: crudBy;
    /**
     * @generated from protobuf field: CategoryRestaurantProto.crudBy updatedBy = 8;
     */
    updatedBy?: crudBy;
    /**
     * @generated from protobuf field: CategoryRestaurantProto.crudBy deletedBy = 9;
     */
    deletedBy?: crudBy;
    /**
     * @generated from protobuf field: string createdAt = 10;
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updatedAt = 11;
     */
    updatedAt: string;
    /**
     * @generated from protobuf field: bool isDeleted = 12;
     */
    isDeleted: boolean;
    /**
     * @generated from protobuf field: string deletedAt = 13;
     */
    deletedAt: string;
}
/**
 * @generated from protobuf message CategoryRestaurantProto.Image
 */
export interface Image {
    /**
     * @generated from protobuf field: string image_custom = 1;
     */
    imageCustom: string;
    /**
     * @generated from protobuf field: string image_cloud = 2;
     */
    imageCloud: string;
}
/**
 * @generated from protobuf message CategoryRestaurantProto.crudBy
 */
export interface crudBy {
    /**
     * @generated from protobuf field: string _id = 1;
     */
    Id: string;
    /**
     * @generated from protobuf field: string email = 2;
     */
    email: string;
}
/**
 * @generated from protobuf message CategoryRestaurantProto.ReqFindCatResByArrId
 */
export interface ReqFindCatResByArrId {
    /**
     * @generated from protobuf field: repeated string arrIdCatRes = 1;
     */
    arrIdCatRes: string[];
    /**
     * @generated from protobuf field: string catResId = 2;
     */
    catResId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ReqFindOneCatRes$Type extends MessageType<ReqFindOneCatRes> {
    constructor() {
        super("CategoryRestaurantProto.ReqFindOneCatRes", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "catResId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CategoryRestaurantProto.ReqFindOneCatRes
 */
export const ReqFindOneCatRes = new ReqFindOneCatRes$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CategoryRestaurantModel$Type extends MessageType<CategoryRestaurantModel> {
    constructor() {
        super("CategoryRestaurantProto.CategoryRestaurantModel", [
            { no: 1, name: "cat_res_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "cat_res_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "cat_res_slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "cat_res_icon", kind: "message", T: () => Image },
            { no: 5, name: "cat_res_short_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "cat_res_status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "createdBy", kind: "message", T: () => crudBy },
            { no: 8, name: "updatedBy", kind: "message", T: () => crudBy },
            { no: 9, name: "deletedBy", kind: "message", T: () => crudBy },
            { no: 10, name: "createdAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "updatedAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "isDeleted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 13, name: "deletedAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CategoryRestaurantProto.CategoryRestaurantModel
 */
export const CategoryRestaurantModel = new CategoryRestaurantModel$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Image$Type extends MessageType<Image> {
    constructor() {
        super("CategoryRestaurantProto.Image", [
            { no: 1, name: "image_custom", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "image_cloud", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CategoryRestaurantProto.Image
 */
export const Image = new Image$Type();
// @generated message type with reflection information, may provide speed optimized methods
class crudBy$Type extends MessageType<crudBy> {
    constructor() {
        super("CategoryRestaurantProto.crudBy", [
            { no: 1, name: "_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CategoryRestaurantProto.crudBy
 */
export const crudBy = new crudBy$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReqFindCatResByArrId$Type extends MessageType<ReqFindCatResByArrId> {
    constructor() {
        super("CategoryRestaurantProto.ReqFindCatResByArrId", [
            { no: 1, name: "arrIdCatRes", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "catResId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CategoryRestaurantProto.ReqFindCatResByArrId
 */
export const ReqFindCatResByArrId = new ReqFindCatResByArrId$Type();
/**
 * @generated ServiceType for protobuf service CategoryRestaurantProto.CategoryRestaurantServiceGprc
 */
export const CategoryRestaurantServiceGprc = new ServiceType("CategoryRestaurantProto.CategoryRestaurantServiceGprc", [
    { name: "findOneCatRes", options: {}, I: ReqFindOneCatRes, O: IBackendGRPC },
    { name: "findCatResByArrId", options: {}, I: ReqFindCatResByArrId, O: IBackendGRPC }
]);
