// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "employee.proto" (package "EmployeeProto", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EmployeeServiceGprc } from "./employee";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { IBackendGRPC } from "./api";
import type { ReqFindOneEmployById } from "./employee";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service EmployeeProto.EmployeeServiceGprc
 */
export interface IEmployeeServiceGprcClient {
    /**
     * @generated from protobuf rpc: findOneEmployeeById(EmployeeProto.ReqFindOneEmployById) returns (api.IBackendGRPC);
     */
    findOneEmployeeById(input: ReqFindOneEmployById, options?: RpcOptions): UnaryCall<ReqFindOneEmployById, IBackendGRPC>;
}
/**
 * @generated from protobuf service EmployeeProto.EmployeeServiceGprc
 */
export class EmployeeServiceGprcClient implements IEmployeeServiceGprcClient, ServiceInfo {
    typeName = EmployeeServiceGprc.typeName;
    methods = EmployeeServiceGprc.methods;
    options = EmployeeServiceGprc.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: findOneEmployeeById(EmployeeProto.ReqFindOneEmployById) returns (api.IBackendGRPC);
     */
    findOneEmployeeById(input: ReqFindOneEmployById, options?: RpcOptions): UnaryCall<ReqFindOneEmployById, IBackendGRPC> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReqFindOneEmployById, IBackendGRPC>("unary", this._transport, method, opt, input);
    }
}
