// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "employee.proto" (package "EmployeeProto", syntax proto3)
// tslint:disable
import { IBackendGRPC } from "./api";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message EmployeeProto.ReqFindOneEmployById
 */
export interface ReqFindOneEmployById {
    /**
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * @generated from protobuf field: string eplResId = 2;
     */
    eplResId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ReqFindOneEmployById$Type extends MessageType<ReqFindOneEmployById> {
    constructor() {
        super("EmployeeProto.ReqFindOneEmployById", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "eplResId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message EmployeeProto.ReqFindOneEmployById
 */
export const ReqFindOneEmployById = new ReqFindOneEmployById$Type();
/**
 * @generated ServiceType for protobuf service EmployeeProto.EmployeeServiceGprc
 */
export const EmployeeServiceGprc = new ServiceType("EmployeeProto.EmployeeServiceGprc", [
    { name: "findOneEmployeeById", options: {}, I: ReqFindOneEmployById, O: IBackendGRPC }
]);
