// @generated by protobuf-ts 2.9.4 with parameter long_type_string,optimize_code_size
// @generated from protobuf file "helloWorld.proto" (package "HelloWorld", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message HelloWorld.GetHelloWorldRequest
 */
export interface GetHelloWorldRequest {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
}
/**
 * @generated from protobuf message HelloWorld.GetHelloWorldResponse
 */
export interface GetHelloWorldResponse {
    /**
     * @generated from protobuf field: string message = 1;
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetHelloWorldRequest$Type extends MessageType<GetHelloWorldRequest> {
    constructor() {
        super("HelloWorld.GetHelloWorldRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message HelloWorld.GetHelloWorldRequest
 */
export const GetHelloWorldRequest = new GetHelloWorldRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetHelloWorldResponse$Type extends MessageType<GetHelloWorldResponse> {
    constructor() {
        super("HelloWorld.GetHelloWorldResponse", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message HelloWorld.GetHelloWorldResponse
 */
export const GetHelloWorldResponse = new GetHelloWorldResponse$Type();
/**
 * @generated ServiceType for protobuf service HelloWorld.HelloWorldService
 */
export const HelloWorldService = new ServiceType("HelloWorld.HelloWorldService", [
    { name: "GetHelloWorld", options: {}, I: GetHelloWorldRequest, O: GetHelloWorldResponse }
]);
